import re
with open('main.py', 'r', encoding='utf-8') as f: text = f.read()
text = text.replace('ft.colors.with_opacity(0.6, ft.colors.WHITE)', '"#99ffffff"')
text = text.replace('ft.colors.with_opacity(0.8, ft.colors.WHITE)', '"#ccffffff"')
text = text.replace('ft.colors.with_opacity(0.5, ft.colors.WHITE)', '"#80ffffff"')
text = text.replace('ft.colors.with_opacity(0.4, ft.colors.WHITE)', '"#66ffffff"')
text = text.replace('ft.colors.with_opacity(0.3, ft.colors.WHITE)', '"#4dffffff"')
text = text.replace('ft.colors.with_opacity(0.2, ACTION_COLOR)', '"#330078d4"')
text = text.replace('ft.colors.BLACK87', 'ft.Colors.BLACK_87')
text = text.replace('ft.colors.', 'ft.Colors.')
with open('main.py', 'w', encoding='utf-8') as f: f.write(text)
print('Fixed Flet colors API changes!')
