import os
import time
import urllib.request
import zipfile
import subprocess
import shutil

class DependencyManager:
    def __init__(self, bin_path: str, logger=None):
        self.bin_path = bin_path
        self.logger = logger
        
        self.yt_dlp = os.path.join(self.bin_path, "yt-dlp.exe")
        self.ffmpeg = os.path.join(self.bin_path, "ffmpeg.exe")
        self.deno = os.path.join(self.bin_path, "deno.exe")
        
        if not os.path.exists(self.bin_path):
            os.makedirs(self.bin_path)

    def log(self, message: str):
        if self.logger:
            self.logger.log(message)
        else:
            print(message)

    def verify_and_download(self):
        self.clean_old_files()
        
        if not os.path.exists(self.yt_dlp):
            self.download_yt_dlp()
            
        if not os.path.exists(self.ffmpeg):
            self.download_ffmpeg()
            
        if not os.path.exists(self.deno):
            self.download_deno()

    def clean_old_files(self):
        """Clean up deno.old.exe generated by deno upgrade."""
        deno_old = os.path.join(self.bin_path, "deno.old.exe")
        if os.path.exists(deno_old):
            try:
                os.remove(deno_old)
                self.log("Cleaned up old deno executable.")
            except Exception as e:
                self.log(f"Warning: Could not remove {deno_old}: {e}")

    def download_yt_dlp(self):
        self.log("Downloading yt-dlp.exe...")
        try:
            url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"
            urllib.request.urlretrieve(url, self.yt_dlp)
            self.log("yt-dlp.exe downloaded successfully.")
        except Exception as e:
            if self.logger: self.logger.handle_error(e, "YT-DLP Download")
            
    def download_ffmpeg(self):
        self.log("Downloading FFmpeg (this may take a minute or two)...")
        try:
            url = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
            zip_path = os.path.join(self.bin_path, "ffmpeg.zip")
            urllib.request.urlretrieve(url, zip_path)
            
            self.log("Extracting FFmpeg...")
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                for file_info in zip_ref.infolist():
                    if file_info.filename.endswith('ffmpeg.exe'):
                        file_info.filename = "ffmpeg.exe" # extract directly to bin_path
                        zip_ref.extract(file_info, self.bin_path)
                        break
                        
            os.remove(zip_path)
            self.log("FFmpeg downloaded and extracted successfully.")
        except Exception as e:
            if self.logger: self.logger.handle_error(e, "FFmpeg Download")

    def download_deno(self):
        self.log("Downloading Deno...")
        try:
            url = "https://github.com/denoland/deno/releases/latest/download/deno-x86_64-pc-windows-msvc.zip"
            zip_path = os.path.join(self.bin_path, "deno.zip")
            urllib.request.urlretrieve(url, zip_path)
            
            self.log("Extracting Deno...")
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extract("deno.exe", self.bin_path)
                
            os.remove(zip_path)
            self.log("Deno downloaded and extracted successfully.")
        except Exception as e:
            if self.logger: self.logger.handle_error(e, "Deno Download")

    def update_apps_if_needed(self, ui_callback_start=None, ui_callback_end=None):
        update_flag = os.path.join(self.bin_path, "last_update.txt")
        current_time = time.time()
        
        if os.path.exists(update_flag):
            try:
                with open(update_flag, "r") as f:
                    last_update = float(f.read().strip())
                    if current_time - last_update < 86400:
                        self.log("--- Bin apps are up to date (checked recently) ---")
                        return
            except:
                pass

        self.log("--- Checking for updates for bin apps ---")
        if ui_callback_start:
            ui_callback_start()
            
        if os.path.exists(self.yt_dlp):
            try:
                self.log("Updating yt-dlp...")
                subprocess.run([self.yt_dlp, "-U"], check=False, creationflags=0x08000000)
            except Exception as e:
                self.log(f"Error updating yt-dlp: {e}")
                
        if os.path.exists(self.deno):
            try:
                self.log("Updating deno...")
                subprocess.run([self.deno, "upgrade"], check=False, creationflags=0x08000000)
            except Exception as e:
                self.log(f"Error updating deno: {e}")
                
        try:
            with open(update_flag, "w") as f:
                f.write(str(current_time))
        except:
            pass

        if ui_callback_end:
            ui_callback_end()
